source "https://rubygems.org"



gem 'ffi', '~> 1.15', '>= 1.15.4'
gem 'thor', '~> 1.1'
gem 'colorize', '~> 0.8.1'

platforms :mingw, :x64_mingw, :mswin, :jruby do
  gem "tzinfo", "~> 1.2"
  gem "tzinfo-data"
end

gem "wdm", "~> 0.1.1", :platforms => [:mingw, :x64_mingw, :mswin]