source 'https://rubygems.org'

gem 'base64'
gem 'colorize', '~> 0.8.1'
gem 'ffi', '~> 1.15', '>= 1.15.4'
gem 'thor', '~> 1.1'
gem 'toml', '~> 0.3.0'

gem 'solargraph', group: :development

platforms :mingw, :x64_mingw, :mswin, :jruby do
  gem 'tzinfo', '~> 1.2'
  gem 'tzinfo-data'
end

gem 'wdm', '~> 0.1.1', platforms: %i[mingw x64_mingw mswin]
