set(CMAKE_C_COMPILER ${TCC} -B${TCC_LIBAR} -I${TCC_LIBC} -I${TCC_LIBTCC})
set(CMAKE_C_COMPILER_ID ${TCC} -B${TCC_LIBAR} -I${TCC_LIBC} -I${TCC_LIBTCC})
set(CMAKE_C_COMPILER_WORKS 1)
set(CMAKE_C_COMPILER_ID_WORKS 1)
