title: 3BC LANG

author: Rodrigo Dornelles

baseurl: "/"
url: "https://3bc-lang.org"

description: >- 
  3BC Lang is Low level language,
  tiny virtual machine that works on computers and microcontrollers.
  (Friendly Punched cards)

plugins:
  - jekyll-optional-front-matter
  - jekyll-titles-from-headings
  - jekyll-github-metadata
  - jekyll-default-layout
  - jekyll-relative-links
  - jekyll-redirect-from
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-feed
  - jemoji
