source "https://rubygems.org"

gem "jekyll", "~> 3.9.0"

group :jekyll_plugins do
  gem "github-pages", "~> 209"
  gem 'jekyll-optional-front-matter'
end

platforms :mingw, :x64_mingw, :mswin, :jruby do
  gem "tzinfo", "~> 1.2"
  gem "tzinfo-data"
end

gem "wdm", "~> 0.1.1", :platforms => [:mingw, :x64_mingw, :mswin]
