enum error_e {
    ERROR_CPU_ZERO = 2,
    ERROR_CPU_UNDEF,
    ERROR_CPU_PROTECT,
    ERROR_CPU_RESERVED,
    ERROR_CPU_REGISTER,
    ERROR_CPU_INVALID,
    ERROR_INVALID_LABEL,
    ERROR_INVALID_VALUE,
    ERROR_INVALID_ADDRESS,
    ERROR_PARAM_DUALITY, 
    ERROR_PARAM_REQUIRE_VALUE,
    ERROR_PARAM_REQUIRE_ADDRESS,
    ERROR_PARAM_BLOCKED_VALUE,
    ERROR_PARAM_BLOCKED_ADDRESS,
    ERROR_INTERPRETER_REGISTER,
    ERROR_INTERPRETER_NUMBER,
    ERROR_TAPE_LABEL,
    ERROR_TAPE_MEMORY,
    ERROR_TAPE_PROGRAM,
    ERROR_TAPE_SORT,
    ERROR_INVALID_MEMORY_CONFIG,
    ERROR_INVALID_MEMORY_CLAMP,
    ERROR_VOID_HELPER_MAX_MIN
};

typedef enum error_e error_t;