if(DEFINED CMAKE_SYSTEM_VERSION)
    if(${CMAKE_SYSTEM_VERSION} STREQUAL "nes")
        set(CMAKE_EXECUTABLE_SUFFIX_C ".nes")
    endif()

    if(${CMAKE_SYSTEM_VERSION} STREQUAL "c64")
        set(CMAKE_EXECUTABLE_SUFFIX_C ".prg")
        set(CONIO TRUE)
    else()
        set(CONIO FALSE)
    endif()

    if(${CMAKE_SYSTEM_VERSION} STREQUAL "windows")
        set(CMAKE_EXECUTABLE_SUFFIX_C ".exe")
        set(WIN32 TRUE)
    else()
        set(WIN32 FALSE)
    endif()

    if(${CMAKE_SYSTEM_VERSION} STREQUAL "linux")
        set(LINUX TRUE)
    else()
        set(LINUX FALSE)
    endif()

    if(${CMAKE_SYSTEM_VERSION} STREQUAL "darwin")
        set(APPLE TRUE)
        set(POSIX TRUE)
    else()
        set(APPLE FALSE)
    endif()

    if(${CMAKE_SYSTEM_VERSION} MATCHES "bsd")
        set(UNIX TRUE)
        set(POSIX TRUE)
    else()
        set(UNIX FALSE)
    endif()
endif()
