include_directories("${CMAKE_SOURCE_DIR}/src")
include_directories("${CMAKE_SOURCE_DIR}/src/bus")
include_directories("${CMAKE_SOURCE_DIR}/src/cpu")
include_directories("${CMAKE_SOURCE_DIR}/src/ds")
include_directories("${CMAKE_SOURCE_DIR}/src/pkg")
include_directories("${CMAKE_SOURCE_DIR}/src/sys")
include_directories("${CMAKE_SOURCE_DIR}/src/i18n")
include_directories("${CMAKE_SOURCE_DIR}/src/types")
