message("##################################")
message("##              ##    ##        ##")
message("##              ##    ##        ##")
message("##              ##    ##    ######")
message("############    ##    ##    ######")
message("############    ##    ##    ######")
message("##              ##    ##        ##")
message("##              ##    ##        ##")
message("##              ##    ############")
message("############    ##              ##")
message("############    ##              ##")
message("##              ##    ######    ##")
message("##              ##    ######    ##")
message("##              ##              ##")
message("##################################")
message("\nCopyright (C) 2020 Rodrigo Dornelles.\n")
