if(NOT TARGET)
set(TARGET "native")
endif()

if(${TARGET} MATCHES "cc65-(.+)")
    set(CC65_TARGET ${CMAKE_MATCH_1})
    include("${CMAKE_SOURCE_DIR}/cmake/find/cc65.cmake")
    set(CMAKE_C_FLAGS "-t ${CC65_TARGET} ${CMAKE_C_FLAGS}")
    set(CMAKE_TOOLCHAIN_FILE "${CMAKE_SOURCE_DIR}/cmake/toolchain/cc65.cmake")
    set(CMAKE_EXECUTABLE_SUFFIX_C ".${CC65_TARGET}")
    message("-- using cc65 cross compiler.\n")
elseif(${TARGET} MATCHES "zig-(.+)")
    set(ZIG_TARGET ${CMAKE_MATCH_1})
    include("${CMAKE_SOURCE_DIR}/cmake/find/zig.cmake")
    if(${TARGET} MATCHES "windows")
        set(CMAKE_EXECUTABLE_SUFFIX_C ".exe")
    endif()
    set(CMAKE_TOOLCHAIN_FILE "${CMAKE_SOURCE_DIR}/cmake/toolchain/zig.cmake")
    message("-- using zig cross compiler.")
elseif(${TARGET} STREQUAL native)
    unset(CMAKE_TOOLCHAIN_FILE)
    message("-- using host native compiler.")
    message("-- NOTE: for distribution use '-DTARGET=<compiler>-<system>-<arch>-<abi>'\n")
else()
    message(FATAL_ERROR "target '${TARGET}' its not supported at the moment." )
endif()
