if(NOT TARGET)
set(TARGET "native")
endif()

if(${TARGET} STREQUAL nes)
    include("${CMAKE_SOURCE_DIR}/cmake/find/cc65.cmake")
    include("${CMAKE_SOURCE_DIR}/cmake/find/cc65.cmake")
    set(CMAKE_C_FLAGS  "-t ${TARGET} ${CMAKE_C_FLAGS}")
    set(CMAKE_TOOLCHAIN_FILE "${CMAKE_SOURCE_DIR}/cmake/toolchain/cc65.cmake")
    set(CMAKE_EXECUTABLE_SUFFIX_C ".nes")
    message("-- using cc65 cross compiler.\n")
elseif(${TARGET} STREQUAL native)
    unset(CMAKE_TOOLCHAIN_FILE)
    message("-- using host native compiler.")
    message("-- NOTE: for distribution use '-DTARGET=release-<system>-<arch>-<abi>'\n")
else()
    message(FATAL_ERROR "target '${TARGET}' its not supported at the moment." )
endif()
