option(TEST_SIZES "Test: sizes" OFF)
option(TEST_SIZES "Test: unit" OFF)

if(DEFINED TESTS)
    if(${TESTS} MATCHES "sizes")
        set(TEST_SIZES ON)
    endif()
    if(${TESTS} MATCHES "unit")
        set(TEST_UNIT ON)
    endif()
endif()

if(TEST_SIZES)
    include(CTest)
    add_executable("test_sizes_primitives" "${CMAKE_SOURCE_DIR}/tests/sizes/primitives.c")
    add_test(NAME "primitives_sizes" COMMAND "test_sizes_primitives")
endif()

if(TEST_UNIT)
    include(CTest)
    add_executable("test_cast_itos" "${CMAKE_SOURCE_DIR}/tests/unit/test_cast_itos.c")
    target_link_libraries("test_cast_itos" "tbc_cast")
    add_test(NAME "cast_itos" COMMAND "test_cast_itos")
endif()
