if(NOT CMAKE_HOST_SYSTEM_PROCESSOR)
    execute_process(
        COMMAND uname -m
        OUTPUT_VARIABLE ARCH
        OUTPUT_STRIP_TRAILING_WHITESPACE
    )
    set(CMAKE_HOST_SYSTEM_PROCESSOR "${ARCH}")
endif()

if(NOT CMAKE_HOST_SYSTEM_PROCESSOR)
    message(WARNING "host system processor not detected.")
    set(CMAKE_HOST_SYSTEM_PROCESSOR_AARCH64 "x86_64")
elseif(CMAKE_HOST_SYSTEM_PROCESSOR STREQUAL "arm")
    set(CMAKE_HOST_SYSTEM_PROCESSOR_AARCH64 "aarch64")
else()
    set(CMAKE_HOST_SYSTEM_PROCESSOR_AARCH64 "${CMAKE_HOST_SYSTEM_PROCESSOR}")
endif()
