if(NOT CMAKE_HOST_SYSTEM_PROCESSOR)
    execute_process(
        COMMAND uname -m
        OUTPUT_VARIABLE ARCH
        COMMAND_ERROR_IS_FATAL ANY
        OUTPUT_STRIP_TRAILING_WHITESPACE
    )
    set(CMAKE_HOST_SYSTEM_PROCESSOR "${ARCH}")
endif()

if(CMAKE_HOST_SYSTEM_PROCESSOR STREQUAL "arm")
    set(CMAKE_HOST_SYSTEM_PROCESSOR_AARCH64 "aarch64")
else()
    set(CMAKE_HOST_SYSTEM_PROCESSOR_AARCH64 "${CMAKE_HOST_SYSTEM_PROCESSOR}")
endif()
