name: Automatic tests
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  fast: 
    runs-on: ubuntu-latest
    steps:
      - name: Checkout project
        uses: actions/checkout@v2
    
      - name: Run fast tests suite
        run: make tests
  full: 
    runs-on: ubuntu-latest
    steps:
      - name: Checkout project
        uses: actions/checkout@v2
    
      - name: Run full tests suite
        run: make tests-full

      - name: Report tests
        run: |
          gcov unit.c
          bash <(curl -s https://codecov.io/bash)
