name: Compiler gcc
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  linux: 
    runs-on: ubuntu-latest
    steps:
      - name: Checkout project
        uses: actions/checkout@v2
        
      - name: Build project
        run: gcc programs/interpreter.c -lm -O0

  macos10: 
    runs-on: macos-10.15
    steps:
      - name: Checkout project
        uses: actions/checkout@v2
        
      - name: Build project
        run: gcc programs/interpreter.c -O0

  macos11: 
    runs-on: macos-11
    steps:
      - name: Checkout project
        uses: actions/checkout@v2
        
      - name: Build project
        run: gcc programs/interpreter.c -O0

  windows: 
    runs-on: 	windows-latest
    steps:
      - name: Checkout project
        uses: actions/checkout@v2
        
      - name: Build project
        run: gcc programs/interpreter.c -O0
